GET http://localhost:5007/listings

###
GET http://localhost:5007/listings/64cf743819ad22b379fd0622

###

GET http://localhost:5007/listings?minPrice=3000

###

GET http://localhost:5007/listings?minPrice=1700&maxPrice=1890

###

GET http://localhost:5007/listings/64cf75b5e827bee1e1b471d3

###

POST http://localhost:5007/listings
Content-Type: application/json

{
    "name": "New Home 3",
    "description": "very nice home stay",
    "price": 1233,
    "currency": "INR"
}

###

PUT  http://localhost:5007/listings/64df5cb6c47b9432ec020770
Content-Type: application/json

{
    "name": "New Home 5",
    "description": "Lavish stays",
    "price": 77777,
    "currency": "INR"
}

###

PATCH http://localhost:5007/listings/64df5cb6c47b9432ec020770
Content-Type: application/json

{
    "description":"indian lavish 7 star stays"
}

###
PATCH http://localhost:5007/listings/64cf7d0d1d942657cbc50094
Content-Type: application/json

{
    "name":"continental"
}

###

DELETE http://localhost:5007/listings/64cf75b5e827bee1e1b471d3

###

DELETE http://localhost:5007/listings/64cf7d191d942657cbc50096

